groups:
  - name: cpu_alerts
    rules:
    - alert: HighCpuUsage
      expr: 100 - (avg by(system_cpu_logical_number) (irate(system_cpu_utilization{job="backend-client-metric", system_cpu_state="idle"}[1m])) * 100) > 1
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage detected on {{ $labels.system_cpu_logical_number }} of Client API"
        description: "CPU usage is above 80% for 1 minute (currently {{ $value }}%)"